### ISSUE TITLE
how to pass event handlers to child component

### ISSUE THREAD

**Issue by appsdevpk** [jegan321/nuro#16]
i created a child component adp-button and bind a simple click event to it, but that event didn't fired?

**Comment by jegan321** [comment]
If the method is defined in the parent component, you have to pass the method as a prop to the child component. Then in the child component you can use `@click` to have the click event call the passed in method. Here is an example:

```js
    class App {
      template = `
        <div>
          <h1>Click the button</h1>
          <adp-button :action="sayHello"></adp-button>
        </div>
      `
      includes = {
        AdpButton
      }
      sayHello() {
        alert('Hello!')
      }
    }

    class AdpButton {
      template = `
        <button @click="props.action">
          Click Me
        </button>
      `
    }

    Nuro.mount(App)
```

Note the colon before the prop name in the parent template. If you do `action="sayHello"` instead of `:action="sayHello"` then it will pass the literal string `sayHello` instead of the method with that name.

**Comment by appsdevpk** [comment]
Thanks a lot, i am creating a side project using this framework, will tell you soon about it when finished

**Comment by jegan321** [comment]
That's awesome! I'm excited to see what you make.
